version: '3'

services:
    nginx:
        restart: unless-stopped
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - news-portal
    php:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - news-portal
    postgres:
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: pg-user
            POSTGRES_PASSWORD: pg-pass
            POSTGRES_DB: pg-db
        ports:
            - "5436:5432"
        restart: unless-stopped
        networks:
            - news-portal
networks:
    news-portal: